import_sorter:
  emojis: true
  custom_order:
    - Dart
    - Blank
    - Flutter
    - Blank
    - Package
    - Blank
    - Project
    - Relative
  ignored_files:
    - 'test/**'
    - '**/*.g.dart'